"""Broadcast a hub release to consumers (plan P4-3).

After a release, regenerate the business repo's `skill-memory.lock` (semver +
SHA) and (with --open-pr) open a PR to pin the new version. The lock content is
deterministic and testable; opening the PR is a thin stub here (GitHub API),
mirroring `hmopt sediment --open-pr` — the design keeps broadcast half-automatic.

CLI:
    python tools/broadcast.py --hub-version=0.2.0 [--sha=<sha>] [--mode=in-repo]
                              [--lock-path=<path>] [--apply] [--open-pr]
"""
from __future__ import annotations

import sys
from pathlib import Path

HUB = Path(__file__).resolve().parent.parent
DEFAULT_LOCK = HUB.parent / ".opencode" / "skill-memory.lock"


def lock_content(hub_version: str, sha: str = "HEAD", mode: str = "in-repo",
                 path: str = "../hm-skill-hub", url: str = "") -> str:
    """Render a skill-memory.lock pinning the hub. `in-repo` until the subtree
    split; `submodule` after (carries url + full sha + semver)."""
    head = ("# Pin file: locks the hub version this business repo consumes.\n"
            "# Generated by hm-skill-hub/tools/broadcast.py (Phase 4).\n")
    if mode == "submodule":
        body = (f"mode: submodule\n"
                f"url: {url}\n"
                f"semver: {hub_version}\n"
                f"sha: {sha}\n")
    else:
        body = (f"mode: in-repo\n"
                f"path: {path}\n"
                f"pin: {sha}\n"
                f"hub_version: {hub_version}\n")
    return head + body


def write_lock(lock_path: str | Path, hub_version: str, sha: str = "HEAD",
               mode: str = "in-repo", url: str = "") -> str:
    content = lock_content(hub_version, sha=sha, mode=mode, url=url)
    p = Path(lock_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return content


def main(argv: list[str]) -> int:
    def opt(name: str, default: str = "") -> str:
        return next((a.split("=", 1)[1] for a in argv if a.startswith(f"--{name}=")), default)

    hub_version = opt("hub-version")
    if not hub_version:
        sys.stderr.write("usage: broadcast.py --hub-version=<semver> [--sha=..] [--apply] [--open-pr]\n")
        return 2
    sha = opt("sha", "HEAD")
    mode = opt("mode", "in-repo")
    url = opt("url")
    lock_path = Path(opt("lock-path", str(DEFAULT_LOCK)))
    apply = "--apply" in argv
    content = lock_content(hub_version, sha=sha, mode=mode, url=url)
    print(content)
    if apply:
        lock_path.parent.mkdir(parents=True, exist_ok=True)
        lock_path.write_text(content, encoding="utf-8")
        print(f"wrote {lock_path}")
    if "--open-pr" in argv:
        # Stub: real impl opens a PR to the business repo via the GitHub API.
        print(f"[stub] would open PR to business repo: pin hub {hub_version} (sha {sha})")
    if not apply:
        print("(dry-run; pass --apply to write the lock)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
