"""Scorecard dashboard (plan P4-4): per-skill score trend, GitHub-rendered.

Scans every `skills/**/scorecards/*.json`, groups by skill, sorts by semver, and
renders `eval/scorecards/_dashboard.md` — a quick view of whether each skill's
`pass_rate` / `mean_score` is trending up (the signal that feeds the
auto-merge trust threshold, P4-5).

CLI:
    python tools/dashboard.py [--apply]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HUB = Path(__file__).resolve().parent.parent


def _semver(v: str) -> tuple[int, int, int]:
    m = re.match(r"(\d+)\.(\d+)\.(\d+)", str(v))
    return tuple(int(x) for x in m.groups()) if m else (0, 0, 0)  # type: ignore[return-value]


def collect_scorecards(hub_root: str | Path = HUB) -> dict[str, list[dict]]:
    root = Path(hub_root) / "skills"
    by_skill: dict[str, list[dict]] = {}
    if not root.exists():
        return by_skill
    for p in sorted(root.rglob("scorecards/*.json")):
        try:
            card = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        by_skill.setdefault(str(card.get("skill", p.parent.parent.name)), []).append(card)
    for cards in by_skill.values():
        cards.sort(key=lambda c: _semver(c.get("version", "0.0.0")))
    return by_skill


def _arrow(delta: float) -> str:
    if delta > 1e-9:
        return f"▲ +{delta:.2f}"
    if delta < -1e-9:
        return f"▼ {delta:.2f}"
    return "= 0.00"


def render(by_skill: dict[str, list[dict]]) -> str:
    lines = ["# Skill scorecard dashboard", "",
             "_Auto-generated by `tools/dashboard.py`. Per-skill eval trend; ▲ = improving._", ""]
    if not by_skill:
        lines.append("_(no scorecards yet)_")
        return "\n".join(lines) + "\n"
    for skill in sorted(by_skill):
        cards = sorted(by_skill[skill], key=lambda c: _semver(c.get("version", "0.0.0")))
        latest = cards[-1]
        lines += [f"## `{skill}` — latest {latest.get('version')} "
                  f"(pass_rate {latest.get('pass_rate', 0):.2f}, suite `{latest.get('suite', '')}`)",
                  "", "| version | pass_rate | mean | n | Δ pass_rate |",
                  "|---|---|---|---|---|"]
        prev = None
        for c in cards:
            pr = float(c.get("pass_rate", 0.0))
            delta = pr - prev if prev is not None else 0.0
            lines.append(f"| {c.get('version')} | {pr:.2f} | {float(c.get('mean_score', 0)):.2f} "
                         f"| {c.get('n', 0)} | {_arrow(delta) if prev is not None else '—'} |")
            prev = pr
        lines.append("")
    return "\n".join(lines) + "\n"


def write_dashboard(hub_root: str | Path = HUB) -> Path:
    """Render + write the dashboard for `hub_root` (parameterized for nightly)."""
    by_skill = collect_scorecards(hub_root)
    out = Path(hub_root) / "eval" / "scorecards" / "_dashboard.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(by_skill), encoding="utf-8")
    return out


def main(argv: list[str]) -> int:
    by_skill = collect_scorecards(HUB)
    if "--apply" in argv:
        out = write_dashboard(HUB)
        print(f"wrote {out} ({len(by_skill)} skill(s))")
    else:
        print(render(by_skill))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
